# Generated by Django 4.1.7 on 2023-07-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SP', 'Sport news'), ('WT', 'Weather news'), ('PL', 'Politics news'), ('ED', 'Education news'), ('EC', 'Economics news'), ('FS', 'Fashion news')], default='WT', help_text='category name', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.author', verbose_name='Author name'),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='News.category', verbose_name='This is the help text')),
            ],
        ),
    ]
