# Generated by Django 4.1.7 on 2023-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_category_name_alter_post_author_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(choices=[('SP', 'Sport news'), ('WT', 'Weather news'), ('PL', 'Politics news'), ('ED', 'Education news'), ('EC', 'Economics news'), ('FS', 'Fashion news')], default='WT', help_text='category name', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(choices=[('SP', 'Sport news'), ('WT', 'Weather news'), ('PL', 'Politics news'), ('ED', 'Education news'), ('EC', 'Economics news'), ('FS', 'Fashion news')], default='WT', help_text='category name', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
