# Generated by Django 4.1.7 on 2023-07-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_category_name_en_category_name_ru_mymodel_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('SP', 'Sport news'), ('WT', 'Weather news'), ('PL', 'Politics news'), ('ED', 'Education news'), ('EC', 'Economics news'), ('FS', 'Fashion news')], default='WT', help_text='category name', max_length=2),
        ),
    ]
