# Generated by Django 4.1.7 on 2023-07-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_post_title_en_post_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_post_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text_post_ru',
            field=models.TextField(null=True),
        ),
    ]
