# Generated by Django 4.1.7 on 2023-07-25 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_post_text_post_en_post_text_post_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
    ]
